[package]
name = "serializer_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "2.0.68"
quote = "1.0"
proc-macro2 = "1.0.86"
log = "0.4.*"
